name: GetSober Shot
favicon: null
layout_spectrum: 0.53323
typography_spectrum: 0.88259
title: "GetSober Shot - THE WORLD'S BEST HANGOVER PREVENTION & CURE"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1199af'
    - '#040707'
    - '#e1e2e3'
    - '#d21a20'
    - '#95979a'
  brandStrength: 0.2995122531428933
  lightness: 0.8287678561173379
  saturation: 0.12223081942647696
  rhythmicContrast: 0.6101427697576582
purpose: []
